import java.awt.*;
public class MenuExample {
Frame frame;
public MenuExample() {
		frame=new Frame("BVRITH");
		MenuBar mb=new MenuBar();
		Menu stud=new Menu("Students");
		Menu cse=new Menu("CSE");
		Menu it=new Menu("IT");
		Menu ece=new Menu("ECE");
		Menu eee=new Menu("EEE");
		stud.add(cse);
		stud.add(it);
		stud.add(ece);
		stud.add(eee);
		Menu a=new Menu("YEAR I");
		Menu b=new Menu("YEAR II");
		Menu c=new Menu("YEAR III");
		Menu d=new Menu("YEAR IV");
		cse.add(a);
		cse.add(b);
		cse.add(c);
		cse.add(d);
		Menu e=new Menu("YEAR I");
		Menu f=new Menu("YEAR II");
		Menu g=new Menu("YEAR III");
		Menu h=new Menu("YEAR IV");
		it.add(e);
		it.add(f);
		it.add(g);
		it.add(h);
		Menu i=new Menu("YEAR I");
		Menu j=new Menu("YEAR II");
		Menu k=new Menu("YEAR III");
		Menu l=new Menu("YEAR IV");
		ece.add(i);
		ece.add(j);
		ece.add(k);
		ece.add(l);
		Menu m=new Menu("YEAR I");
		Menu n=new Menu("YEAR II");
		Menu o=new Menu("YEAR III");
		Menu p=new Menu("YEAR IV");
		eee.add(m);
		eee.add(n);
		eee.add(o);
		eee.add(p);
		MenuItem q=new MenuItem("SECTION A");
		MenuItem r=new MenuItem("SECTION B");
		MenuItem s=new MenuItem("SECTION C");
		a.add(q);
		a.add(r);
		a.add(s);
		MenuItem t=new MenuItem("SECTION A");
		MenuItem u=new MenuItem("SECTION B");
		MenuItem v=new MenuItem("SECTION C");
		b.add(t);
		b.add(u);
		b.add(v);
		MenuItem x=new MenuItem("SECTION A");
		MenuItem y=new MenuItem("SECTION B");
		MenuItem z=new MenuItem("SECTION C");
		c.add(x);
		c.add(y);
		c.add(z);
		MenuItem aa=new MenuItem("SECTION A");
		MenuItem bb=new MenuItem("SECTION B");
		MenuItem cc=new MenuItem("SECTION C");
		d.add(aa);
		d.add(bb);
		d.add(cc);
		MenuItem dd=new MenuItem("SECTION A");
		MenuItem ee=new MenuItem("SECTION B");
		MenuItem ff=new MenuItem("SECTION C");
		e.add(dd);
		e.add(ee);
		e.add(ff);
		MenuItem gg=new MenuItem("SECTION A");
		MenuItem hh=new MenuItem("SECTION B");
		MenuItem ii=new MenuItem("SECTION C");
		f.add(gg);
		f.add(hh);
		f.add(ii);
		MenuItem jj=new MenuItem("SECTION A");
		MenuItem kk=new MenuItem("SECTION B");
		MenuItem ll=new MenuItem("SECTION C");
		g.add(jj);
		g.add(kk);
		g.add(ll);
		MenuItem mm=new MenuItem("SECTION A");
		MenuItem nn=new MenuItem("SECTION B");
		MenuItem oo=new MenuItem("SECTION C");
		h.add(mm);
		h.add(nn);
		h.add(oo);
		MenuItem pp=new MenuItem("SECTION A");
		MenuItem qq=new MenuItem("SECTION B");
		MenuItem rr=new MenuItem("SECTION C");
		i.add(pp);
		i.add(qq);
		i.add(rr);
		MenuItem ss=new MenuItem("SECTION A");
		MenuItem tt=new MenuItem("SECTION B");
		MenuItem uu=new MenuItem("SECTION C");
		j.add(ss);
		j.add(tt);
		j.add(uu);
		MenuItem vv=new MenuItem("SECTION A");
		MenuItem ww=new MenuItem("SECTION B");
		MenuItem xx=new MenuItem("SECTION C");
		k.add(vv);
		k.add(ww);
		k.add(xx);
		MenuItem a1=new MenuItem("SECTION A");
		MenuItem b1=new MenuItem("SECTION B");
		MenuItem c1=new MenuItem("SECTION C");
		l.add(a1);
		l.add(b1);
		l.add(c1);
		MenuItem d1=new MenuItem("SECTION A");
		MenuItem e1=new MenuItem("SECTION B");
		MenuItem f1=new MenuItem("SECTION C");
		m.add(d1);
		m.add(e1);
		m.add(f1);
		MenuItem g1=new MenuItem("SECTION A");
		MenuItem h1=new MenuItem("SECTION B");
		MenuItem i1=new MenuItem("SECTION C");
		n.add(g1);
		n.add(h1);
		n.add(i1);
		MenuItem j1=new MenuItem("SECTION A");
		MenuItem k1=new MenuItem("SECTION B");
		MenuItem l1=new MenuItem("SECTION C");
		o.add(j1);
		o.add(k1);
		o.add(l1);
		MenuItem m1=new MenuItem("SECTION A");
		MenuItem n1=new MenuItem("SECTION B");
		MenuItem o1=new MenuItem("SECTION C");
		p.add(m1);
		p.add(n1);
		p.add(o1);
		mb.add(stud);
		frame.setMenuBar(mb);
		frame.setLayout(null);
		frame.setVisible(true);
		frame.setSize(400,400);
	}
public static void main(String args[]) {
	MenuExample m1=new MenuExample();
}
}
